version: "3"

services:
  server:
    image: "jet1oeil-server"
    environment:
      - UDEV=1
    privileged: true
    ports:
      - "25000:25000"
    volumes:
      - "./config:/home/jet1oeil-server/:rw"

